### ISSUE TITLE
Pulling out network characteristics

### ISSUE THREAD

**Issue by anthonymobile** [MattSilas/Wifi-Scanner#1]
So the OSX part doesn't seem to be working anymore on 10.10

the first string is now the Country Code
MAC address is second and SSID is third.

i'm still getting my feet wet with python, but changing the findall [1] to a [2] to get the SSID threw a list out of range error. is there a way to simply select the data for that 'SSID_STR' element?

also, any idea how to set a flag for any network with NONE for encryption?

thanks useful start

**Comment by anthonymobile** [comment]
mmm i think this was my mistake.

**Comment by MattSilas** [comment]
No you are correct, OS X 10.10 changed the plist outputs for a number of utilities. I've updated this to reflect those changes and also made the whole OS X functionality more robust and customizable. It gets everything back from the scan and tosses it into a single dictionary, so you can choose which items are needed for you
